language: python
python:
  - "2.7"
install:
  - pip install cherrypy
  - touch owndc/routing/__init__.py
  - pip install -e .
script:
  # - owndc &
  - python2 tests/testRoute.py
  - python2 tests/testDataselect.py
  # - python2 -m unittest tests.testService
