language: python
python:
  - "2.7"
install:
  - pip install cherrypy
  - pip install -e .
script:
  # - owndc &
  - python -m unittest tests.testRoute
  - python -m unittest tests.testDataselect
  # - python2 -m unittest tests.testService
